### ISSUE TITLE
[Bug] Error 419 Insufficient space on Resource

### ISSUE THREAD

**Issue by luismarquezzini** [laracasts/cypress#13]
Hello, what do when i get this error?

I just try to use execute a cy.refreshDatabase() or any php command for that matter and i get this error when i execute cypress

![image](https://user-images.githubusercontent.com/16675397/92793920-49a56f00-f385-11ea-8edb-ac5f273120b7.png)

**Comment by ilkermutlu** [comment]
419 is likely due to a lack of csrf_token, at least it was in my case.

**Comment by Krisell** [comment]
The "insufficient space on resource" is one interpretation of 419 that is probably not at all correct in this case. Laravel uses 419 for CSRF issues or "Session expired".

See here for the same issue: https://github.com/cypress-io/cypress/issues/950
