### ISSUE TITLE
[Question/Issue] Working with Livewire component

### ISSUE THREAD

**Issue by RomainGoncalves** [laracasts/cypress#19]
Hi,

when I try to type some text into a Livewire component, I somehow get immediately disconnected. 
I can see in the console that the route for the component gets hit, and a 419 Unknown response is returned, which disconnects the user.

Please see the screenshot for details.

<img width="421" alt="Screenshot 2020-10-14 at 18 49 41" src="https://user-images.githubusercontent.com/1366477/96020257-08095780-0e4e-11eb-873f-9c867bf843f9.png">

Did I forget something in the configuration?

thanks

**Comment by JeffreyWay** [comment]
I use this package to test a few Livewire components, and haven't had any issues. 

I think this might be an issue with your Livewire component, and not a bug in the package.

**Comment by bhulsman** [comment]
I'm running into the same issue, did you find a solution for this?
