### ISSUE TITLE
CypressError: cy.its() only accepts a single argument.

### ISSUE THREAD

**Issue by splatEric** [laracasts/cypress#25]
I've just setup using this package, and am receiving the above error message when I try to invoke one of the Laravel integration commands. The source of the error is in the `laravel-commands.js`, when the CSRF Token is retrieved. It currently reads:

```
Cypress.Commands.add('csrfToken', () => {
    return cy
        .request({
            method: 'GET',
            url: '/__cypress__/csrf_token',
            log: false,
        })
        .its('body', { log: false });
});
```

If I remove the `{ log: false }` argument to `its` the command works successfully.

Of course I can get it to work this way, as I can simply remove this option specification in my published copy of the commands (I am assuming I will have this issue across the board where this pattern is used). 

I am posting this as information for others, but also to see if anyone else has seen this and if there's a better solution to the problem?

I am using the official docker containers for cypress for actually invoking my tests (rather than a local install of cypress), but I don't believe that should be having an impact.

Bit new to cypress though, so very aware that I could be missing a subtlety in the setup.

**Comment by Krisell** [comment]
What version of Cypress are you using? I think updating will resolve this, we run the same code without any issues.
Also see here: https://github.com/cypress-io/cypress/issues/1450

**Comment by splatEric** [comment]
oh dear, I hang my head in shame. 

It's absolutely the docker container I am using, it's very out of date.

Thanks for taking the time to respond @Krisell much appreciated.
