### ISSUE TITLE
Unable to Locate Factory

### ISSUE THREAD

**Issue by e10a** [laracasts/cypress#27]
I'm getting this error
`InvalidArgumentException: Unable to locate factory for [App\User]. in file`

From login_spec.js file containing
```
    before(() => {
        cy.refreshDatabase().seed();

        cy.create("App\\User", {
            first_name: "First",
            last_name: "Last",
            email: "name@example.com",
            password: "password",
        });
    });
```
I'm able to get past the error if I comment out the following in CypressController.php
```
    protected function factoryBuilder($model)
    {
        // Should we use legacy factories?
        // if (class_exists('Illuminate\Database\Eloquent\Factory')) {
        //     return factory($model);
        // }

        return (new $model())->factory();
    }
}
```

Has anyone else come across this?

My project has the following dependencies
- php: ^7.4
- laravel/legacy-factories: ^1.1
- cypress: ^7.2.0
- laracasts/cypress: ^1.3
- laravel/framework: ^8.0

Error occurs with or without `laravel/legacy-factories: ^1.1`

**Comment by dillingham** [comment]
@e10a are your models in `App \\Models\\User` by chance?
