### ISSUE TITLE
Strange issue with .env configurations

### ISSUE THREAD

**Issue by maurocasas** [laracasts/cypress#30]
Hello!

Thank you very much for this amazing contribution!

I've been coming across a really strange issue which I'm not being able to debug..
For some reason, when booting Cypress and doing the `before()` JS callback, when it clears out the config it's placing information which isn't anywhere to be seen.

It's auto-injecting `forge` for database username and database name, as well as hard-setting my environment to `production`, which is causing some issues with my tests.

Has anyone had this issue?

Thank you!

**Comment by Krisell** [comment]
Do you have a `.env.cypress` file? If so, it swaps .env with that.

**Comment by J4si3k** [comment]
I have this problem too, I understand that ```swap-env.js``` should replace these files. However, this does not work for me. When executing some test, the settings from .env.cypress are copied to .env and as a result I have e.g. wrong DB_DATABASE
