### ISSUE TITLE
[Discussion] Gitlab Pipeline

### ISSUE THREAD

**Issue by robsontenorio** [laracasts/cypress#31]
Has anyone managed to get the Gitlab pipeline to work?

It fails when cypress try to get `http://localhost:8080/__cypress__/csrf_token` (not found)

```yaml
script: 
    - ... other steps ...    
    - yarn cypress:run (fails here when try to get /__cypress__/csrf_token)
```

So, manually I have tried to  get with some urls
```yaml
script: 
    - curl http://localhost:8080/posts  (works)
    - curl http://localhost:8080/users (works)
    - curl http://localhost:8080/__cypress__/csrf_token (fail)
```

**Comment by Krisell** [comment]
I suppose you're installing composer dev-dependencies, and not setting the environment to `production` when running this (otherwise, the routes from this package are not registered)?

**Comment by robsontenorio** [comment]
@Krisell  My bad! When env is `production` for sure this route `__cypress__` won't  work.
