### ISSUE TITLE
500 and 404 HTTP Errors after setup

### ISSUE THREAD

**Issue by marcuschristiansen** [laracasts/cypress#36]
I'm running this package inside a Laravel 8 application with Sail.

The tests very sporadically tend to pass then after re-running them they fail with the following error messages.

```
cy.request() failed on:

http://digiam.test/cypress/artisan

The response we received from your web server was:

  > 500: Internal Server Error
```

![Screenshot 2021-09-09 at 17 25 50](https://user-images.githubusercontent.com/8204622/132715277-c5b51e4e-ed4e-4844-8c49-57dd9653acd1.png)

I also occasionally get 404 errors.

I've noticed that the routes are registered as :
\_\_cypress\_\_/artisan and \_\_cypress\_\_/csrf_token but cypress seem to try to access /cypress/artisan and cypress/csrf_token

My only test file under integration/patients is 

```
describe('Creating a new patient', () => {
    beforeEach(() => {
        cy.login({ email: 'marcus@testemail.com' })
    })

    it('works', () => {
        cy.visit({ route: 'patients.create' }).contains('Create a new patient')
    })
})
```

**Comment by Krisell** [comment]
If you're getting a 500 response, you can read the server logs to see the actual issue. If the 500 is generated by Laravel, you find this by default in `storage/logs`.

**Comment by marcuschristiansen** [comment]
I am however still getting 404 errors for route /cypress/artisan even though it is registered.

**Comment by jxjj** [comment]
In case it helps anyone else, I had the similar error because I was using [`cy.login`](https://github.com/laracasts/cypress#cylogin) incorrectly.

I was doing this:
```php
// ❌ BAD! 
cy.login('test_user');
```

Once I changed it to this, it worked as expected:

```php
// ✅ GOOD! 
cy.login({ username: 'test_user' });
```

Thanks for another great Laravel project!
