### ISSUE TITLE
using the php command

### ISSUE THREAD

**Issue by AbrahamBrookes** [laracasts/cypress#38]
I am having mixed results with the cy.php command bundled with this library. I'll often get this error:

`CypressError: Timed out retrying after 4000ms: `cy.its()` errored because the property: `result` does not exist on your subject.`

Which I had deduced was happening due to the php I am executing not returning a value, but that assumption has been challenged a bunch of times to the point where I really have no idea what that error represents.

Is there a particular interface I should be adhering to when using the cy.php command and when returning data from the php I am executing therein?

**Comment by azurinspire** [comment]
It seems to wait some kind of return value always, I was having the same problem when attaching two models together and easiest fix I found is null coalescing operator:

```js
cy.php(`App\\Models\\Program::find(${program.id})->tags()->attach(${tag.id}) ?? true`);
```
