### ISSUE TITLE
Assertion proxy for phpunit & http assertions

### ISSUE THREAD

**Issue by dillingham** [laracasts/cypress#4]
Firstly, awesome package! Really enjoying the quick familiarity it brings my laravelian brain.

I was curious about the possibility of magic methods that just send to php

```
cy.php(`assertOk()`).then(outcome => {
    expect(outcome).to.equal(true); 
});
```
Like behind the scenes it makes phpunit calls & asserts outcomes behind a helper method

Maybe pestphp would help since it's syntax is similar, not super familiar with it.

Would be a cool way to avoid duplicating all the stuff.

**Comment by JeffreyWay** [comment]
Eh, I think that's probably a bit too far for my taste.
