### ISSUE TITLE
Alternative factory syntax proposal

### ISSUE THREAD

**Issue by dillingham** [laracasts/cypress#42]
proposed parameter syntax using object keys:
```js
cy.create({
    model: 'App\\Models\\Post',
    fill: {title: 'I override factory default'},
    with: ['author'],
    state: ['published'],
    count: 50
}).then(post => {

})
```
The current parameter list
```js
cy.create('App\\Models\\Post', { title: 'I override factory default' }, ['author']);
```

- Allows stacked parameters for more readable parameter list
- Allows more obvious parameters via object keys, `with` returns the relation
- Avoids 4th parameter for a much needed factory `state` or `count` parameter

Additionally would love if `cy.visit` automatically detects an object and uses `id`

`{ route: 'posts.show', post }` becomes  `{route: 'posts.show', parameters: { post: post.id } }` 

```js
cy.create({
    model: 'App\\Models\\Post',
}),then(post => {
    cy.visit({ route: 'posts.show , post})
});
```

**Comment by JeffreyWay** [comment]
Yeah, I think we *do* need an optional alternative syntax. I'll try to work on this today.

**Comment by JeffreyWay** [comment]
This should be done now. 👍
