### ISSUE TITLE
Use the models that were just created

### ISSUE THREAD

**Issue by jeroenvanrensen** [laracasts/cypress#48]
Hello everyone,

I'm new to Cypress and I want a test that a user can see its projects after signing in.

I tried to save the user, but this does not work:

```js
it('can see its projects', () => {
    let user = cy.login()
    let project = cy.create('App\\Models\\Project', { user_id: user.id })
    cy.visit('/home').contains(project.name)
})
```

However, this does work:

```js
it('can see its projects', () => {
    cy.login().then(user => {
        cy.create('App\\Models\\Project', { user_id: user.id }).then(project => {
            cy.visit('/home').contains(project.name)
        })
    })
})
```

Is the last one the only way to do this, or are there other ways to save the just created models?

**Comment by JeffreyWay** [comment]
No, you shouldn't need to do that in Cypress. Cypress runs commands serially. So something like this will work: 

```
  it('shows a post', () => {
    cy.create('Laracasts\\Post', { title: 'My First Post' });

    cy.visit('/posts').contains('My First Post');
  });
```

If that's not working on your end, I'm not sure what to say. If you can break it down to a very simple and reproducible example, we can try to help.

**Comment by jeroenvanrensen** [comment]
Hello, do you mean I should do this?

```js
it('can see its projects', () => {
    cy.login({ id: 1 })
    cy.create('App\\Models\\Project', { user_id: 1, name: 'My Project' })
    cy.visit('/home').contains('My Project')
})
```

**Comment by JeffreyWay** [comment]
Yes, that should work.

**Comment by jeroenvanrensen** [comment]
Okay thanks!

**Comment by troccoli** [comment]
I'm sorry about commenting on a closed issue, but I too would like to be able to use the model just created.

In my case I have a post and I want to check that the correct data is shown: title, author, date, content, etc.

Your suggestion would mean I had to specify each field I want to check
```js
cy.create({model: 'App\\Models\\Post', attributes: {title: 'My post', content: ' My content', author: ' Giulio'}}
```

Apart from being very verbose, we don't use factories to their full potential. If we could get the object created it would be much clearer

```js
const post = cy.create({model: 'App\\Models\\Post'});

cy.visit('/post/' + post.id).get('#title').should('contain', post.title);
```

This doesn't work, but it would be very helpful if it would.
