### ISSUE TITLE
Problems with Passport command `passport:install` does not exist

### ISSUE THREAD

**Issue by danielrmsantos** [laracasts/cypress#52]
I'm struggling to call the artisan command `passport:install` or any `passport` command with the following error:
`Symfony\Component\Console\Exception\CommandNotFoundException: The command &quot;passport:install&quot; does not exist. in file /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php on line 190`

On my test I'm trying:
`beforeEach(() => {
    cy.refreshDatabase()
    cy.artisan('migrate', { '--path': 'vendor/laravel/passport/database/migrations' })
    cy.artisan('passport:install')
    cy.seed()
  })`

Am I missing something or it's just not possible to run passport commands from the tests?
I'm using Laravel 9 and PHP 8.1

**Comment by danielrmsantos** [comment]
@JeffreyWay any thoughts on this issue? Any help is welcome, thank you.

**Comment by JeffreyWay** [comment]
I have no idea, but this probably isn't the best place to ask a Passport integration question.
