### ISSUE TITLE
There are no commands defined in the "cypress" namespace. 

### ISSUE THREAD

**Issue by MtDalPizzol** [laracasts/cypress#53]
I'm getting a `There are no commands defined in the "cypress" namespace. ` error after installing and trying to run the `cypress:boilerplate` command.

Already tried this:

```
php artisan config:clear
php artisan cache:clear
composer dump-autoload
```

**Comment by MtDalPizzol** [comment]
Just found out the reason for that:

I have a scenario where I can't have an `.env` file and instead I have specific files for each environment (`.env.local`, `.env.cypress`, `.env.production`).

It seams that the package requires an `.env` file for running. Just created one and the command ran.

I'll leave this open until the maintainers decide if this ia a bug or expected behavior.

**Comment by Krisell** [comment]
In that case the command wasn't registered because the environment defaults to `production` unless `APP_ENV` is set, and this package only registers routes and commands in a local environment for security reasons.

**Comment by MtDalPizzol** [comment]
Closing because it is expected behavior.
