### ISSUE TITLE
Global installation of Cypress

### ISSUE THREAD

**Issue by fvelcker** [laracasts/cypress#59]
Hello,

Anyway to handle Cypress installed globally?
I have a prebuilt devcontainer shared across the team where cypress is installed globally, so it is available for any type projects, and I can use that same container in the pipeline.
But here it assumes Cypress is installed locally.

Thanks,

**Comment by i-bajrai** [comment]
Might be better to ask in the cypress repo https://github.com/cypress-io/cypress.

But maybe this will help?

https://docs.npmjs.com/downloading-and-installing-packages-globally

**Comment by fvelcker** [comment]
I don't have any issue with installing Cypress or Cypress in general.
My issue is to be able to use this package, laracasts/cypress, Cypress needs to be installed locally, otherwise it can't be initialized.

**Comment by JeffreyWay** [comment]
Happy to accept a PR. Otherwise, right now, it expects that Cypress is installed locally.
