### ISSUE TITLE
[Feature][Documentation] Execute more complex php

### ISSUE THREAD

**Issue by WalrusSoup** [laracasts/cypress#6]
I had a need to add more complex helpers during the setup phase to assist in generating additional users, admins, etc prior to the test running.

For example, I have the need to test that one admin cannot edit another admin user. For this, I need to seed two users into the database and check that one does not have access to edit the other. Was considering copying the service provider structure used by this package like so:

```php
class CypressHelperServiceProvider extends ServiceProvider
{
    public function boot()
    {
        if ($this->app->environment('production')) {
            return;
        }
        $this->addRoutes();
    }


    protected function addRoutes()
    {
        Route::namespace('')
            ->middleware('web')
            ->group(base_path('Tests/Cypress/routes/cypress_helpers.php'));
    }
}
```
Then in the route area
```php
return [
    // Create new admin user and assign all permissions
Route::post('/__cypress__/createAdmin', [CypressHelperController::class, 'createAdmin'])->name('cypress.create.admin'),
    // Login via a given email address
    Route::post('/__cypress__/loginByEmail', [CypressHelperController::class, 'loginByEmail'])->name('cypress.login.email'),
    // Login via a given ID
    Route::post('/__cypress__/loginById', [CypressHelperController::class, 'loginById'])->name('cypress.login.id'),
];
```

Then in AppServiceProvider.php
```php
 public function register()
    {
        if (config('app.env') !== 'production') {
            // Other service providers
            $this->app->register(CypressHelperServiceProvider::class);
        }
    }
```
Directory like so:

![image](https://user-images.githubusercontent.com/5719851/90987370-65181980-e53f-11ea-8f77-28eaaa3eaf2d.png)

Example Controller
```php
use Laracasts\Cypress\Controllers\CypressController;
use Spatie\Permission\Models\Permission;

class CypressHelperController extends CypressController
{
    public function createAdmin(Request $request)
    {
        $user = factory($this->userClassName())
            ->create($request->input('attributes', []));
        $user->setRole('admin');
        auth()->login($user);
        return $user;
    }

    public function loginByEmail(Request $request)
    {
        $user = User::find(['email' => $request->get('email')]);
        auth()->login($user);
        return $user;
    }

    public function loginById(Request $request)
    {
        $user = User::find($request->get('id'));
        auth()->login($user);
        return $user;
    }
}
```

Does this appear to be the correct approach for handling this requirement? If so, I can contribute some documentation to help others or update the package to publish some of these assets so users can just drop in their more complex requirements.

**Comment by iamniels** [comment]
Looks great to me.

For Laravel 6+ you don't need to register the service provider. It is done automatically after composer dump-autoload.

Now your package depends on Spatie Permissions, make this optional. Many people don't use this package.

Instead of createAdmin action you could make an setRole($role, $userId) action. It is more versatile.

**Comment by WalrusSoup** [comment]
That was simply an example of how I implemented it. I'll work on some general documentation for this approach and PR it into the library. Closing this for now as it seems like the best approach.
