### ISSUE TITLE
Class "App\User" not found

### ISSUE THREAD

**Issue by Jamesking56** [laracasts/cypress#65]
Hi,

First time using this package, I'm on Laravel 9.

I have the pre-built User model in `App\User`, so I did this to try and create a user in my test:

```js
describe('workouts index', () => {
  it('allows us to see a list of workouts', () => {
    cy.create('App\\User', { attributes: { email: 'john.doe@example.com' }});
  });
});
```

But I get an error in Cypress:

```
Error: Class "App\User" not found in file /home/jamesking56/PhpstormProjects/<project>/vendor/laracasts/cypress/src/Controllers/CypressController.php on line 124
```

Any ideas what I'm doing wrong here?

**Comment by taboritis** [comment]
I am pretty sure that your model is not in in namespace `App` but you have to check `App\Models`

**Comment by Jamesking56** [comment]
Whoops yes working now, thats what happens when you code late at night :sleeping:
