### ISSUE TITLE
Improve safety of environment check

### ISSUE THREAD

**Issue by scottbedard** [laracasts/cypress#79]
Currently, our service provider checks the environment and disables everything if it is `production`.
https://github.com/laracasts/cypress/blob/86b523e313c37e6b156131b63a90fc3a1197c5c4/src/CypressServiceProvider.php#L12-L14

This is probably fine for most situations, but one of my projects uses "prod" instead of "production". I think we should reverse this logic to only _permit_ cypress testing in given environments, rather than _prohibiting_ it. This would be more flexible, and would be a safer default that protects against values other than "production".

If approved, I'll put together a PR that changes the following.

```diff
- if ($this->app->environment('production')) {
+ if (in_array($this->app->environment(), explode(',', env('CYPRESS_ENVIRONMENTS')))) {
     return;
  }
```

This will give us more control with our environment files

```
CYPRESS_ENVIRONMENTS=local,testing
```

Unfortunately though, this is a breaking change. But given the gotcha I encountered of `'prod' != 'production'` and how serious the security implications would have been, I think it is worth it. One option however to avoid the breaking change is to only apply this logic _if_ a `CYPRESS_ENVIRONMENTS` value exists, and otherwise fall back to assume "production". Either way, the documentation should still be updated to improve awareness of environment names.

**Comment by Krisell** [comment]
Note that the string `'production'` is hardcoded in a few places in the Laravel framework for similar protections (e.g. not running the database seeder by mistake in production).

There is also a `isProduction()` method on the `app` instance, also checking if the env is the string `'production'`.

**Comment by scottbedard** [comment]
> e.g. not running the database seeder by mistake in production

Oh wow, I didn't realize this. Ok, I think my safest option is to definitely just refactor my project to always use "production". It might still be worth noting in the docs that we're using this exact name, but for now we can close this issue. Thanks @Krisell!
